### ISSUE TITLE
Whenever `declsUniqueNames` is disabled, we produce invalid TLA+

### ISSUE THREAD

**Issue by VictorCMiraldo** [tweag/pirouette#47]
The `declsUniqueNames` function is supposed to be a nice-to-have feature so that the TLA+ code we produce can be read by humans a little more easily, disabling it should simply yield less nice-to-read TLA+ code but it should still work. This shows we're relying a little too much on assumptions about naming and we have to investigate this.

**Comment by GuillaumeGen** [comment]
When I disable `declsUniqueNames` I get two families of errors.
 - Some symbols in the skeleton are not recognized (For instance `True7` is declared in the file, but `True` is used in the skeleton). I don't think we should address this. The skeleton is intended to be written after getting some information on the TLA produced.
 - The ``--ty-spz` option assumes some standard names for the constructors/destructor of the type we are specializing. I can fix this, if requested.

**Comment by VictorCMiraldo** [comment]
Thanks for investigating! I just came across this issue and wanted to document it at least :)

Agreed about the skeleton; if the errors come from the skeleton it's not pirouette's fault; Fixing the specializer to not assume names would be a nice-to-have but its certainly not a blocker.
