### ISSUE TITLE
Deeper SMT embedding plan

### ISSUE THREAD

**Issue by serras** [tweag/pirouette#81]
Given that Pirouette puts a lot of effort in monomorphizing and defunctionalizing, it makes sense to translate even more things from the Pirouette world into the SMT world. There are two goals:

1. Improve the reasoning capabilities of Pirouette; the more we put in the SMT, the more we can get out.
2. Expose the notion of _uninterpreted function_ from SMT into Pirouette; this would allow us to track information about values which is not necessarily reflected as pure data.

The following is a step-by-step plan for doing so:

- [X] Fix the story around `translateData`, and generalize it to use the complete definition environment (#80 added a test on that direction). Done in #79.
- [X] Introduce all functions defined in a Pirouette code block as uninterpreted functions in the SMT; use them when performing the translation of terms. The end result should be that only `Abs` and `Lam` -- which should have been mostly erased in previous transformation -- give raise to an error in the translation to SMT. Done in #82. **⚠️ Working with it has shown that `match` should not be translated, instead we should only evaluate on WHNF.**
- [ ] Introduce a very simplistic way to stop recursion for going crazy deep (maybe just a list of visited functions?)
- [ ] Introduce a notion of function-without-signature (maybe this can be merged with the next step as simply `assert true`).
- [ ] Introduce an `assert` primitive in the language which can be used to introduce additional constraints in the SMT solver which are known to be true at that point.
- [ ] Example using an `elements` uninterpreted function over a list.

**Comment by VictorCMiraldo** [comment]
@serras, isn't this issue addressed completely in `dev`?

**Comment by serras** [comment]
No, we need to address the recursion-depth problem in a better way, as we discussed during our meeting.

**Comment by VictorCMiraldo** [comment]
I made a dedicated issue with that discussion #90; will close this one.
